- name: Deploy Flask Application
  hosts: web
  become: yes
  tasks:
    - name: Remove conflicting packages
      apt:
        name: containerd
        state: absent
      ignore_errors: yes  # Ignore if not installed

    - name: Update package list
      apt:
        update_cache: yes

    - name: Check if Docker is installed
      command: docker --version
      register: docker_installed
      ignore_errors: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      when: docker_installed is failed

    - name: Build Docker Image
      command: docker build -t my_app /home/piyushpc/my_flask_app/venv

    - name: Run Docker Container
      command: docker run -d -p 5000:5000 my_app

