- name: Deploy Flask Application
  hosts: localhost
  become: yes
  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Remove conflicting containerd if exists
      apt:
        name: containerd
        state: absent
      ignore_errors: yes  # Ignore errors if containerd is not installed

    - name: Ensure necessary packages are installed
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - python3-pip
        - docker-ce

    - name: Install Docker if not installed
      command: docker --version
      register: docker_installed
      ignore_errors: yes

    - name: Install Docker if it's not installed
      apt:
        name: docker.io
        state: present
      when: docker_installed is failed

    - name: Build Docker Image
      command: docker build -t my_app /home/piyushpc/my_flask_app/venv

    - name: Run Docker Container
      command: docker run -d -p 5000:5000 my_app

