- name: Deploy Flask Application
  hosts: localhost
  tasks:
    - name: Gather Facts
      setup:

    - name: Update package list
      apt:
        update_cache: yes

    - name: Build Docker Image
      community.docker.docker_image:
        name: "my_app"
        tag: "latest"
        source: build
        build:
          path: "/var/lib/jenkins/workspace/Deploy Flask App"
          dockerfile: "Dockerfile"

    - name: Run Docker Container
      community.docker.docker_container:
        name: my_app_container
        image: my_app:latest
        state: started
        restart_policy: always

